# Action for running tests
# Generated to match: ./console generate:test-action --plugin="Missivus" --php-versions="matomo6_min_php,matomo6_max_php"
name: Plugin Missivus Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - '**.x-dev'
  workflow_dispatch:

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  issues: read
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

concurrency:
  group: php-${{ github.ref }}
  cancel-in-progress: true

jobs:
  PluginTests:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php: [ 'matomo6_min_php', 'matomo6_max_php' ]
        target: [ 'minimum_required_matomo', 'maximum_supported_matomo' ]
        database:
          - { engine: 'Mysql', version: '8.0' }
          - { engine: 'Mariadb', version: '10.6' }
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          persist-credentials: false
      - name: Run tests
        uses: matomo-org/github-action-tests@main
        with:
          plugin-name: 'Missivus'
          php-version: ${{ matrix.php }}
          test-type: 'PluginTests'
          mysql-engine: ${{ matrix.database.engine }}
          mysql-version: ${{ matrix.database.version }}
          matomo-test-branch: ${{ matrix.target }}
          upload-artifacts: false
